blank_issues_enabled: false
contact_links:
  - name: MinecraftConsoles Community Discord
    url: https://discord.gg/jrum7HhegA
    about: If you need help, please ask for it in our Discord! You will get assistance much faster there, including help getting the project to compile.
